apiVersion: v1
kind: Service
metadata:
  name: flux-server
  namespace: vecsmith
spec:
  selector:
    app.kubernetes.io/name: vecsmith-flux-server
  ports:
    - port: 8081
      targetPort: 8081
      name: http
