"""Tests for SVG optimization stage."""

from src.stages.svg_optimize import optimize_svg


class TestSvgOptimize:
    def test_adds_xml_declaration(self, sample_svg: str):
        result = optimize_svg(sample_svg)
        assert result.startswith('<?xml version="1.0"')

    def test_preserves_viewbox(self):
        svg = (
            '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">'
            '<circle cx="50" cy="50" r="40" fill="blue"/>'
            "</svg>"
        )
        result = optimize_svg(svg)
        assert 'viewBox="0 0 100 100"' in result

    def test_adds_viewbox_from_dimensions(self, sample_svg: str):
        result = optimize_svg(sample_svg)
        assert 'viewBox="0 0 256 256"' in result

    def test_rounds_path_coordinates(self, vtracer_svg: str):
        result = optimize_svg(vtracer_svg, precision=2)
        # Should not contain long decimal numbers
        assert "128.12345" not in result
        assert "48.67891" not in result
        # Should contain rounded versions
        assert "128.12" in result

    def test_strips_xml_declaration(self):
        svg = (
            '<?xml version="1.0" encoding="UTF-8"?>'
            '<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100">'
            '<rect width="100" height="100" fill="red"/>'
            "</svg>"
        )
        result = optimize_svg(svg)
        # Should have exactly one XML declaration
        assert result.count("<?xml") == 1

    def test_strips_comments(self):
        svg = (
            '<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100">'
            "<!-- Generated by vtracer -->"
            '<rect width="100" height="100" fill="red"/>'
            "</svg>"
        )
        result = optimize_svg(svg)
        assert "<!--" not in result

    def test_removes_empty_groups(self):
        svg = (
            '<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100">'
            "<g></g>"
            '<rect width="100" height="100" fill="red"/>'
            "</svg>"
        )
        result = optimize_svg(svg)
        assert "<g" not in result or "<g>" not in result

    def test_handles_invalid_svg_gracefully(self):
        bad_svg = "<not valid xml at all <<<"
        result = optimize_svg(bad_svg)
        # Should return input unchanged
        assert result == bad_svg

    def test_output_is_smaller_or_equal(self, vtracer_svg: str):
        result = optimize_svg(vtracer_svg, precision=1)
        # Rounded coordinates should generally produce smaller output
        # (except for added XML declaration)
        assert isinstance(result, str)
        assert "<svg" in result
