apiVersion: v1
kind: Service
metadata:
  name: vecsmith-frontend
  namespace: vecsmith
spec:
  selector:
    app.kubernetes.io/name: vecsmith-frontend
  ports:
    - port: 80
      targetPort: 3000
      name: http
